# Generated by Django 6.1.1 on 2026-09-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='tag',
            field=models.CharField(choices=[('Gourmet', 'Gourmet'), ('Más Vendido', 'Más Vendido'), ('Sin Azúcar', 'Sin Azúcar'), ('Edición Especial', 'Edición Especial'), ('Novedad', 'Novedad'), ('Tradicional', 'Tradicional')], default='Gourmet', max_length=30, verbose_name='Etiqueta / Tag'),
        ),
        migrations.AlterField(
            model_name='flan',
            name='flan_uuid',
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='flan',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
