# Generated by Django 6.1.1 on 2026-09-22 22:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_flan_tag_alter_flan_flan_uuid_alter_flan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='flan_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
